# Generated by Django 3.1.6 on 2021-02-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Моделииии'},
        ),
        migrations.AddField(
            model_name='model',
            name='title',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
