# Generated by Django 3.1.6 on 2021-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20210209_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Имя'),
        ),
    ]
