# Generated by Django 3.1.6 on 2021-02-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20210209_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Models',
        ),
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
    ]
